### ISSUE TITLE
Prompt user to set default bootloader if undefined when using create or activate

### ISSUE THREAD

**Issue by danboid** [johnramsden/zedenv#17]
Currently zedenv lets the user create a new BE and supposedly activate it before the default bootloader setting has been defined. In my case I had zedenv and the grub plugin installed, running GRUB bl. I created a new BE and tried to activate it but it failed because I forgot to set grub as the default bl with zedenv first.

If autodetecting the bootloader is tricky, then zedenv should prompt the user on how to set the default bootloader before letting them create or activate a BE.

**Comment by johnramsden** [comment]
Well, the idea is that a bootloader plugin isn't strictly necessary. zedenv will still work properly creating the boot environment without a bootloader plugin, the user will just have to change their bootloader config manually.

I guess a warning could be displayed, and the user could be asked if they wanted to continue without a bootloader.

**Comment by danboid** [comment]
This only really applies to grub users and it may only really apply to activating BE's on grub installs because as you say you can still successfully create them without having the default bootloader option set.

**Comment by danboid** [comment]
I've not tried zedenv with systemd bl yet. I presume this isn't an issue in that case?

**Comment by danboid** [comment]
Actually create does not work when using grub if you haven't set the default bootloader for zedenv first.

**Comment by johnramsden** [comment]
Well, it kind of applies. If you don't have a bootloader set with systemd-boot it won't create the bootloader configuration.

Also, you should be able to set a bootloader after the fact and then activate the same be, which should run the necessary setup to create the grub config.

**Comment by johnramsden** [comment]
When you say create doesn't work, what exactly do you mean? It should still create the boot environment.

**Comment by danboid** [comment]
I mean it it shown under ```zedenv list``` but no new grub entry gets created if the grub plugin is installed but the bootloader default isn't set to grub.

**Comment by johnramsden** [comment]
OK, that's working as intended. If you then set a bootloader and activate again, it should create the grub entry.

Maybe I'll change it to just print warning if it's unset and the user tries to create one.

**Comment by danboid** [comment]
So can the default bootloader setting not be done away with entirely, whilst still supporting multiple bootloaders? People can only ever have one bl in use at any one time and aren't going to change it but maybe its tricky detecting which one is in use? Some additional warnings and instructions would be helpful otherwise yes.

**Comment by johnramsden** [comment]
The idea is that boot environments are basically decoupled from the bootloader. All the bootloader plugins are intended to do is basically provide a convenience factor and edit your configs for you. So you could say for example use some other bootloader that isn't supported, create a boot environment, and then manually edit the configs to boot from it.

The default setting is just there so that you don't manually have to use the `--bootloader` flag

I think trying to determine which bootloader is in use would be difficult, and error-prone. Especially since you could have multiple bootloaders installed but only be using one. I can't think of a way to do this in a reliable manner, but I'm open to ideas.

**Comment by danboid** [comment]
We can detect if the user is using UEFI or not. If they are are not using UEFI then we know they are not using sysd boot as it doesn't support BIOS. That narrows it down a bit.

**Comment by danboid** [comment]
So if its not UEFI and they've not set grub as their default bl, print a warning when activate is run to say nothing has happened unless...

**Comment by johnramsden** [comment]
Well, activating without a bootloader plug-in still does do something, it promotes the BE clone, which is the 'activate' part, and set it to the `bootfs`.

I'm not sure I should try to do things differently for each plug-in since the purpose of the plug-in system is that technically anyone could write one for any bootloader and have it work without actually adding any code to `zedenv`.

Right now I'm thinking, when a default boot loader isn't set and the `--bootloader` flag isn't used, I'll print the following message:

> WARNING: Running activate without a bootloader. Re-run with a default bootloader, or with the --bootloader flag. If you plan to manually edit your bootloader config this message can safely be ignored.

**Comment by danboid** [comment]
Sounds good to me!

It's good for people who don't read documentation (yes, they exist! ;), people who did know but forgot (like me) and also those who are coming from FreeBSD where this extra step isn't necessary (with beadm, I've not tried bectl yet) and they might expect zedenv to 'just work' after installation.

**Comment by johnramsden** [comment]
Yeah unfortunately on Linux we don't have the luxury of only having one bootloader that is commonly used, and that you can rely on being there.

It would be nice being able to port the FreeBSD loader since It can actually determine and list any boot environments itself. Could be a good summer project... The last time I looked I had trouble figuring out how to pull all of the code out of the FreeBSD tree. It's too bad the FreeBSD codebase isn't a bit more modular, but I guess it's intended to be a single system.
