### ISSUE TITLE
GrubBE - Booting on zedenv created BE fails with "failed to mount real root device"

### ISSUE THREAD

**Issue by ikidd** [johnramsden/zedenv#19]
I can boot fine to the default entry, but when booting to any of the zedenv created BE entries in GRUB I get that error.

The entry looks like:
linux /ROOT/31-03-19-Update@/boot/vmlinuz-linux root=ZFS=zroot/ROOT/31-03-19-Update rw  radeon.si_support=0 amdgpu.si_support=1 quiet
	echo 'Loading initial ramdisk ...'
	initrd /ROOT/31-03-19-Update@/boot/initramfs-linux.img /ROOT/31-03-19-Update@/boot/intel-ucode.img

[ikidd@archlinux ~]$ zedenv list
Name                      Active   Mountpoint   Creation             
default                   NR       /            Sun-Mar-24-1:51-2019 
Base_Arch_KDE-Linux5.0.4           -            Mon-Mar-25-0:23-2019 
Backup_04-7-19                     -            Sun-Apr-7-11:32-2019 

I mounted that zedenv via zedenv mount and looked at fstab, perhaps I don't understand how the process works but I'd have expected that would have altered the fstab to use the snapshot locations not zroot/ROOT/default still.

I haven't gone through the script well enough to understand what it does yet when it creates a BE and alters GRUB.

**Comment by johnramsden** [comment]
The `zroot/ROOT/31-03-19-Update` dataset doesn't seem to exist - at least it's not being seen by zedenv. Does it show up when you run `zfs list`?

**Comment by ikidd** [comment]
My bad, John, I was keeping track of the grub entries in another file and copypastad the wrong entry to the first message.  I've since burned that 03-31 BE.  Still getting this issue with today's new BE

Grub entry:
```
linux /ROOT/Backup_04-7-19@/boot/vmlinuz-linux root=ZFS=zroot/ROOT/Backup_04-7-19 rw radeon.si_support=0 amdgpu.si_support=1 quiet
initrd /ROOT/Backup_04-7-19@/boot/initramfs-linux.img /ROOT/Backup_04-7-19@/boot/intel-ucode.img
```
zfs list:
```
NAME                                  USED  AVAIL  REFER  MOUNTPOINT
zroot                                11.5G   204G   136K  none
zroot/ROOT                           9.68G   204G   136K  none
zroot/ROOT/Backup_04-7-19             128K   204G  7.35G  /
zroot/ROOT/Base_Arch_KDE-Linux5.0.4   120K   204G  6.60G  /
zroot/ROOT/default                   9.68G   204G  7.35G  /
zroot/boot                           10.5M   204G   136K  none
zroot/boot/grub                      10.4M   204G  10.4M  legacy
zroot/data                           1.83G   204G   136K  none
zroot/data/home                      1.83G   204G  1.83G  legacy
```

**Comment by johnramsden** [comment]
Could you attach the whole `grub.cfg`? Also, does this happen when you activate the boot environment and try to boot into it? Or just when you try to boot from it during the boot sequence when it's not actually active?

Just to make sure this is an entry that has been created by `zedenv` - could you try disabling all of the grub generators in `/etc/grub.d/` except for `00_header` and the `zedenv` generator `05_zfs_linux.py` by removing the executable bits.

Then run `zedenv activate <your be>` and see if that makes a difference.

**Comment by ikidd** [comment]
[grub.cfg.txt](https://github.com/johnramsden/zedenv/files/3052623/grub.cfg.txt)

I can manually activate a BE and it boots fine.  I removed the extra grub generators and made another BE (test1), tried to boot into that at the grub menu with no success.

Edit: I don't know if it makes a difference, but this is a legacy boot, not UEFI.

**Comment by johnramsden** [comment]
Your `grub.cfg` looks correct. I created a test VM and I think I tracked the problem down to `canmount=off`. Can you try setting `zfs set canmount=noauto zroot/ROOT/test1` and giving it another try?

I noticed you said `zroot/ROOT/default` was in your fstab, it actually doesn't actually need to be there since the dataset is being mounted via zfs.

Just to clarify, when you create a new BE, and activate it, you can boot into the new be. The problem you're having is when the BE is _not_ active and you attempt to boot from it.

**Comment by ikidd** [comment]
Yes, that works now, John.  And yes, the issue was when I didn't manually set the activation, I was trying to just use the grub menu to choose which BE to boot.  

Thanks for the help there, I appreciate you following up and working through it with me.  

Did I do something wrong in the setup?  I was using https://github.com/danboid/ALEZ script and he's tried to make it zedenv compatible, I never looked to see if the flags were set according to your directions.

I think that script may set the fstab as well, but I would have done it the same way if I did it manually I'm sure.  In fact, I may have done that and the grub install manually as we were working through some bugs in the script at the time and I was just reading through the script from where it failed and fixing the issues as I finished the script actions manually.

**Comment by johnramsden** [comment]
No, it's actually a bug from how the `zedenv` create command sets new BEs to `canmount=off`, and then sets them to`noauto` on the first activate.

https://github.com/johnramsden/zedenv/blob/8072ee3c7f3e2b3b812dc0c9ac00ee8ff9f4004f/zedenv/cli/create.py#L62

So the bug wouldn't be encountered if you we're trying to switch back to a BE that was previously activated, even if it isn't the currently active BE.

The fix should be as easy as setting the above code to noauto.

Due to how `systemd-boot` menus are only generated on the first activate, I guess I've never ran into this issue.

For now if you create new boot environments you will just have to manually set them to `canmount=noauto` after creation. I should have a fix tested and working quickly though.

**Comment by johnramsden** [comment]
Thanks for your help finding the issue.

**Comment by ikidd** [comment]
Happy to help, thank you for your work on this project, I think it's a very useful tool, especially for recovery issues.  I'd like to figure out how to automate the creation and pruning of backup BEs in a pre-update pacman hook.
